# -*- coding: utf-8 -*-
"""
Gera a tabela estruturada das 28 referencias do artigo BWAIF n. 24960
(SANTOS; BIANCHI; COSTA, 2023 - FinBERT-PT-BR), conforme a orientacao 5.C
do Prof. Emerson (mentoria de 29/07/2026).

Campos exigidos pela orientacao:
  1. Referencia (ABNT)      5. Aplicacao
  2. Encoders/tecnologias   6. Tem relacao com nossa pesquisa?
  3. Objetivo               7. O que podemos aproveitar
  4. Resultados obtidos     8. Data

Saidas: referencias_artigo_bwaif_24960.csv (UTF-8 com BOM, p/ Excel)
"""
import csv
from pathlib import Path

COLUNAS = [
    "#", "Referencia (ABNT)", "Data", "Grupo tematico",
    "Encoders e tecnologias utilizadas", "Objetivo", "Resultados obtidos",
    "Aplicacao", "Relacao com nossa pesquisa", "O que podemos aproveitar",
]

REFS = [
    (1,
     "ARACI, D. FinBERT: financial sentiment analysis with pre-trained language models. arXiv:1908.10063, 2019.",
     "2019", "A - Fundamentos / modelos de dominio",
     "BERT; pre-treino continuado em corpus financeiro; Financial PhraseBank",
     "Adaptar o BERT ao dominio financeiro, mostrando que vocabulario especializado exige modelo especializado.",
     "Supera modelos genericos em analise de sentimento financeiro; estabelece a receita de duas etapas (adaptacao de dominio + ajuste fino).",
     "Analise de sentimento de textos financeiros em ingles.",
     "ALTA",
     "Referencia canonica para justificar a adaptacao de dominio. E o argumento que Santos usa para nao empregar BERT generico - devemos usar o mesmo argumento na fundamentacao."),
    (2,
     "ARDIA, D.; CHOPARD, B.; BOUDT, K. Using Twitter to model the EUR/USD exchange rate. Economics Letters, v. 132, p. 23-26, 2015.",
     "2015", "C - Sentimento e mercado financeiro",
     "Analise de sentimento de tuites; modelagem econometrica de cambio",
     "Modelar a taxa de cambio euro-dolar a partir do sentimento expresso no Twitter.",
     "Sentimento do Twitter apresenta conteudo informacional para o par EUR/USD.",
     "Mercado de cambio.",
     "MEDIA-ALTA",
     "Publicado em periodico de ECONOMIA (nao de computacao) - util para demonstrar a banca que a abordagem tem aceitacao na literatura economica. Trabalhos de cambio costumam tratar volatilidade, o que aproxima do nosso eixo principal."),
    (3,
     "ARTSTEIN, R.; POESIO, M. Inter-coder agreement for computational linguistics. Computational Linguistics, v. 34, n. 4, p. 555-596, 2008.",
     "2008", "E - Metodologia de anotacao",
     "Metricas de concordancia: percentual, Fleiss's Kappa, Krippendorff's alpha",
     "Revisar e formalizar as metricas de concordancia entre anotadores em linguistica computacional.",
     "Consolida vantagens e limitacoes de cada metrica; percentual e enviesado em bases desbalanceadas e pouco robusto para >2 avaliadores.",
     "Construcao e validacao de corpora anotados.",
     "MUITO ALTA",
     "Referencia metodologica que sustenta TUDO o que precisamos corrigir no conjunto-ouro. A monografia de Santos (Secao 2.3.1.2) ja traz as tres formulas transcritas e prontas para adaptacao. LEITURA PRIORITARIA."),
    (4,
     "BOLLEN, J.; MAO, H.; ZENG, X. Twitter mood predicts the stock market. Journal of Computational Science, v. 2, n. 1, p. 1-8, 2011.",
     "2011", "C - Sentimento e mercado financeiro",
     "OpinionFinder; GPOMS; rede neural fuzzy; causalidade de Granger",
     "Verificar se o humor coletivo expresso no Twitter prevê a direcao do mercado acionario dos EUA.",
     "Acuracia declarada de ate 87,6% na previsao de direcao do Dow Jones.",
     "Previsao de direcao de indice acionario.",
     "ALTA",
     "Citacao obrigatoria (artigo fundador da area). RESSALVA ESTRATEGICA: os 87,6% nunca foram replicados de forma robusta e a literatura posterior converge para desempenho de direcao proximo ao acaso - municao direta para reposicionarmos a DIRECAO como resultado negativo e a VOLATILIDADE como contribuicao principal."),
    (5,
     "CHEN, S. F.; BEEFERMAN, D.; ROSENFELD, R. Evaluation metrics for language models. 1998.",
     "1998", "A - Fundamentos / metricas",
     "Perplexidade e metricas de avaliacao de modelos de linguagem",
     "Discutir e comparar metricas de avaliacao intrinseca de modelos de linguagem.",
     "Consolida a perplexidade como metrica de referencia para modelos de linguagem.",
     "Avaliacao intrinseca de modelos de linguagem.",
     "MEDIA (passa a ESSENCIAL se executarmos o MLM de dominio)",
     "E a metrica com que Santos avalia a etapa de adaptacao de dominio (1,51 -> 1,24). Se executarmos o MLM sobre as ~205 mil noticias, esta e a referencia que sustenta a perplexidade como metrica - e a grande vantagem e que ela NAO exige gabarito humano."),
    (6,
     "DE SOUZA, V. A.; DE SOUZA, F.; MEINERZ, G. V. Analise de sentimento em tempo real de noticias do mercado de acoes. Brazilian Journal of Development, v. 7, n. 1, p. 11084-11091, 2021.",
     "2021", "D - Sentimento em portugues",
     "Tecnicas de PLN aplicadas a noticias em portugues, em regime de tempo real",
     "Analisar em tempo real o sentimento de noticias do mercado de acoes brasileiro.",
     "Demonstra viabilidade do processamento de sentimento de noticias em tempo real no contexto brasileiro.",
     "Mercado de acoes brasileiro.",
     "ALTA",
     "Usa NOTICIAS (nao redes sociais) e opera em TEMPO REAL - dialoga diretamente com o nosso recorte de noticias apos as 17h e com o componente de demonstracao do site da pesquisa. Deve entrar na RSL e na tabela de trabalhos relacionados."),
    (7,
     "DEVLIN, J.; CHANG, M.-W.; LEE, K.; TOUTANOVA, K. BERT: pre-training of deep bidirectional transformers for language understanding. arXiv:1810.04805, 2018.",
     "2018", "A - Fundamentos / arquitetura",
     "BERT; masked language modeling (MLM); next sentence prediction",
     "Propor pre-treino bidirecional profundo com objetivo de mascaramento.",
     "Estado da arte em 11 tarefas de PLN a epoca.",
     "Arquitetura-base de todos os encoders utilizados nesta pesquisa.",
     "ALTA",
     "Fornece DOIS hiperparametros operacionais que Santos herda e que devemos usar no nosso MLM de dominio: probabilidade de mascara de 15% e acoplamento da camada de classificacao a primeira dimensao de saida ([CLS]). Tambem e a origem da tecnica de gradual unfreezing citada por Santos."),
    (8,
     "HIEW, J. Z. G.; HUANG, X.; MOU, H.; LI, D.; WU, Q.; XU, Y. BERT-based financial sentiment index and LSTM-based stock return predictability. arXiv:1906.09024, 2019.",
     "2019", "C - Sentimento e mercado financeiro",
     "BERT para sentimento; LSTM para serie temporal de retorno",
     "Construir indice de sentimento financeiro com BERT e avaliar previsibilidade de retorno com LSTM.",
     "Indice de sentimento baseado em BERT apresenta poder preditivo sobre retornos.",
     "Previsao de retorno de acoes.",
     "MUITO ALTA",
     "E a ORIGEM da formula do indice de sentimento adotada por Santos - Indice = (Pos - Neg)/(Pos + Neu + Neg) - e portanto a origem indireta do nosso ISM. E a referencia mais proxima do nosso desenho metodologico em toda a lista. LEITURA INTEGRAL OBRIGATORIA e citacao na fundamentacao do ISM."),
    (9,
     "JANUARIO, B. A.; CAROSIA, A. E. O.; SILVA, A. E. A.; COELHO, G. P. Sentiment analysis applied to news from the Brazilian stock market. IEEE Latin America Transactions, v. 20, n. 3, p. 512-518, 2022.",
     "2022", "D - Sentimento em portugues",
     "PLN aplicado a noticias e tuites do mercado brasileiro",
     "Aplicar analise de sentimento a noticias do mercado de acoes brasileiro.",
     "Resultados aplicados ao mercado brasileiro, combinando tuites e outras fontes de noticia.",
     "Mercado de acoes brasileiro.",
     "MUITO ALTA",
     "E o trabalho BRASILEIRO mais proximo do nosso objeto, publicado em periodico IEEE indexado. LEITURA INTEGRAL OBRIGATORIA: e a referencia contra a qual a banca comparara a nossa contribuicao. Nossa resposta de diferenciacao: ativo unico (PETR4), previsao de VOLATILIDADE e fusao com GARCH."),
    (10,
     "JUNJIE, Z.; MENGONI, P. Spot gold price prediction using financial news sentiment analysis. In: IEEE/WIC/ACM WI-IAT, 2020, p. 758-763.",
     "2020", "C - Sentimento e mercado financeiro",
     "Analise de sentimento de noticias financeiras; modelos preditivos de preco",
     "Prever o preco a vista do ouro a partir do sentimento extraido de noticias financeiras.",
     "Sentimento de noticias contribui para a previsao do preco do ouro.",
     "Previsao de preco de commodity.",
     "MEDIA-ALTA",
     "E o trabalho ESTRUTURALMENTE mais proximo do nosso na lista: commodity unica, NOTICIAS como fonte (nao redes sociais) e previsao de preco. A PETR4 e fortemente acoplada ao petroleo, o que torna o paralelo metodologico direto. LEITURA INTEGRAL RECOMENDADA."),
    (11,
     "KORDONIS, J.; SYMEONIDIS, S.; ARAMPATZIS, A. Stock price forecasting via sentiment analysis on Twitter. In: PCI '16. New York: ACM, 2016.",
     "2016", "C - Sentimento e mercado financeiro",
     "Naive Bayes; SVM; analise de sentimento de tuites",
     "Prever preco de acoes a partir do sentimento no Twitter.",
     "Relacao entre sentimento em redes sociais e movimento de precos.",
     "Previsao de preco de acoes.",
     "MEDIA",
     "Compoe o bloco de trabalhos correlatos baseados em Twitter. Util para justificar por que OPTAMOS POR NOTICIAS e nao por redes sociais - decisao que hoje nao esta formalmente justificada no texto da dissertacao."),
    (12,
     "KRAAIJEVELD, O.; DE SMEDT, J. The predictive power of public Twitter sentiment for forecasting cryptocurrency prices. Journal of International Financial Markets, Institutions and Money, v. 65, art. 101188, 2020.",
     "2020", "C - Sentimento e mercado financeiro",
     "Lexicos de sentimento; deteccao de bots; modelos de previsao",
     "Avaliar o poder preditivo do sentimento publico do Twitter sobre precos de criptomoedas.",
     "Poder preditivo existente porem limitado; forte presenca de bots contamina o sinal.",
     "Previsao de preco de criptomoedas.",
     "MEDIA",
     "A discussao sobre RUIDO E CONTAMINACAO DA FONTE e transponivel a nossa justificativa de usar portais jornalisticos com curadoria editorial em vez de redes sociais."),
    (13,
     "KRIPPENDORFF, K. Content analysis: an introduction to its methodology. 4. ed. Thousand Oaks: Sage, 2018.",
     "2018", "E - Metodologia de anotacao",
     "Krippendorff's alpha; analise de conteudo",
     "Apresentar a metodologia de analise de conteudo, incluindo a metrica alpha de confiabilidade.",
     "Formaliza o alpha, aplicavel a multiplos avaliadores, dados faltantes e diferentes escalas de medida.",
     "Validacao de confiabilidade de bases anotadas.",
     "MUITO ALTA",
     "Fonte primaria do alpha que precisamos passar a reportar. VANTAGEM DECISIVA sobre o kappa de Cohen que usamos hoje: admite numero VARIAVEL de anotadores por item e dados faltantes, ao passo que o kappa exige exatamente 2 anotadores avaliando todos os itens. Como qualquer retomada da rotulagem tera anotadores com disponibilidade desigual, o alpha e a metrica correta para o nosso caso."),
    (14,
     "LIU, B. Sentiment analysis and opinion mining. Synthesis Lectures on Human Language Technologies, v. 5, n. 1, p. 1-167, 2012.",
     "2012", "B - Analise de sentimento: fundamentos",
     "Taxonomia de analise de sentimento; niveis documento/sentenca/aspecto",
     "Sistematizar a area de analise de sentimento e mineracao de opiniao.",
     "Obra de referencia; define os niveis de granularidade da tarefa.",
     "Fundamentacao conceitual.",
     "MEDIA",
     "A distincao entre NIVEIS (documento, sentenca, aspecto) e pertinente a nossa decisao de classificar MANCHETES (nivel de sentenca) em vez de noticias completas (nivel de documento) - decisao que hoje nao esta formalmente justificada na dissertacao."),
    (15,
     "LO, A. W. The adaptive markets hypothesis. The Journal of Portfolio Management, v. 30, n. 5, p. 15-29, 2004.",
     "2004", "C - Fundamentacao teorica em financas",
     "Teoria financeira; hipotese de mercados adaptativos",
     "Reconciliar a hipotese de mercados eficientes com os achados de financas comportamentais.",
     "Precos sao adaptativos e refletem informacoes E emocoes da populacao.",
     "Fundamentacao teorica de financas comportamentais.",
     "ALTA",
     "E a ANCORA TEORICA que justifica a pesquisa inteira: se os mercados fossem perfeitamente eficientes, o sentimento de noticias nao teria conteudo preditivo. Santos abre o artigo com Lo; nossa dissertacao deve fazer o mesmo. Complementar com Fuller (1998), citado na monografia, sobre fontes de alfa."),
    (16,
     "MAN, X.; LUO, T.; LIN, J. Financial sentiment analysis (FSA): a survey. In: IEEE ICPS, 2019, p. 617-622.",
     "2019", "B - Surveys",
     "Revisao de tecnicas de analise de sentimento financeiro",
     "Mapear sistematicamente a area de analise de sentimento financeiro.",
     "Panorama consolidado de abordagens, fontes de dados e aplicacoes.",
     "Mapeamento de area.",
     "ALTA",
     "Survey de referencia para posicionar a nossa RSL. Util para demonstrar a banca que a nossa revisao dialoga com o estado da arte consolidado da area, e nao apenas com trabalhos pontuais."),
    (17,
     "MANNING, C. D.; SCHUTZE, H. Foundations of statistical natural language processing. Cambridge: The MIT Press, 1999.",
     "1999", "A - Fundamentos",
     "PLN estatistico classico",
     "Obra de referencia em processamento estatistico de linguagem natural.",
     "Consolidacao dos fundamentos estatisticos do PLN.",
     "Fundamentacao teorica.",
     "BAIXA",
     "Citacao de enquadramento historico no capitulo teorico, ao definir PLN."),
    (18,
     "MEDEIROS, M.; BORGES, V. Tweet sentiment analysis regarding the Brazilian stock market. In: BraSNAM, 8., 2019. Anais [...]. Porto Alegre: SBC, 2019. p. 71-82.",
     "2019", "D - Sentimento em portugues",
     "Analise de sentimento de tuites em portugues",
     "Analisar o sentimento de tuites relativos ao mercado de acoes brasileiro.",
     "Evidencia de relacao entre sentimento em portugues e mercado brasileiro.",
     "Mercado de acoes brasileiro.",
     "ALTA",
     "Um dos POUCOS trabalhos nacionais na intersecao sentimento x mercado brasileiro. Deve constar da nossa RSL e da tabela de trabalhos relacionados."),
    (19,
     "OTABEK, S.; CHOI, J. Twitter attribute classification with Q-learning on bitcoin price prediction. IEEE Access, v. 10, p. 96136-96148, 2022.",
     "2022", "C - Sentimento e mercado financeiro",
     "Q-learning; aprendizado por reforco; classificacao de atributos de tuites",
     "Prever o preco do bitcoin combinando classificacao de atributos do Twitter com aprendizado por reforco.",
     "Ganho preditivo com selecao de atributos por reforco.",
     "Previsao de preco de criptomoeda.",
     "BAIXA",
     "Pouco aproveitavel diretamente. Registra a fronteira de aprendizado por reforco aplicado a sentimento - eventual mencao em trabalhos futuros."),
    (20,
     "PAGOLU, V. S.; REDDY, K. N.; PANDA, G.; MAJHI, B. Sentiment analysis of Twitter data for predicting stock market movements. In: SCOPES, 2016, p. 1345-1350.",
     "2016", "C - Sentimento e mercado financeiro",
     "Word2Vec; N-gram; Random Forest; SVM; regressao logistica",
     "Prever movimentos do mercado acionario a partir do sentimento de tuites.",
     "Correlacao entre sentimento e movimento de precos; comparacao entre classificadores classicos.",
     "Previsao de direcao de acoes.",
     "ALTA",
     "Usa EXATAMENTE a mesma familia de classificadores da nossa pipeline (SVM, Random Forest, regressao logistica). Referencia direta para justificar as nossas escolhas de modelo e para compor a tabela comparativa de trabalhos relacionados."),
    (21,
     "PANG, B.; LEE, L. A sentimental education: sentiment analysis using subjectivity summarization based on minimum cuts. In: ACL '04, 2004, p. 271-278.",
     "2004", "B - Analise de sentimento: fundamentos",
     "Sumarizacao por subjetividade; cortes minimos em grafos",
     "Melhorar a classificacao de polaridade separando trechos subjetivos de objetivos.",
     "Ganho de desempenho ao filtrar conteudo objetivo antes da classificacao.",
     "Fundamentacao conceitual de analise de sentimento.",
     "MEDIA",
     "Citacao de fundamentacao. A ideia de FILTRAR conteudo objetivo antes de classificar dialoga com o nosso filtro de relevancia (111/300 manchetes marcadas como relevantes a PETR4)."),
    (22,
     "PEREIRA, J. G. Analise de sentimentos da populacao brasileira em relacao a eleicao presidencial de 2018 atraves da rede social Twitter. 2019.",
     "2019", "D - Sentimento em portugues",
     "Analise de sentimento de tuites em portugues",
     "Analisar o sentimento da populacao brasileira sobre a eleicao presidencial de 2018.",
     "Mapeamento de sentimento politico em portugues.",
     "Dominio politico.",
     "BAIXA",
     "Dominio politico, nao financeiro. Serve apenas para ilustrar a amplitude de aplicacao de analise de sentimento em PT-BR."),
    (23,
     "SILVA, M. C. A. Percepcoes sobre corrupcao durante as eleicoes presidenciais no Brasil em 2018: uma analise baseada no Twitter. 2018.",
     "2018", "D - Sentimento em portugues",
     "Analise de sentimento de tuites em portugues",
     "Analisar percepcoes sobre corrupcao durante as eleicoes presidenciais de 2018.",
     "Mapeamento de percepcao publica sobre corrupcao.",
     "Dominio politico.",
     "BAIXA",
     "ATENCAO - RISCO DE CONFUSAO DE REFERENCIA: esta Silva (2018) e sobre percepcao de corrupcao no Twitter e MUITO PROVAVELMENTE NAO e a mesma obra do nosso plano de enriquecimento capitulo a capitulo 'via tese da Silva (2018)'. Conferir a referencia completa antes de qualquer citacao cruzada."),
    (24,
     "SOUZA, F.; NOGUEIRA, R.; LOTUFO, R. BERTimbau: pretrained BERT models for Brazilian Portuguese. In: BRACIS, 2020. p. 403-417.",
     "2020", "A - Fundamentos / modelos PT-BR",
     "BERT base e large para portugues brasileiro; corpus brWaC",
     "Treinar e avaliar modelos BERT pre-treinados para o portugues do Brasil.",
     "BERTimbau supera modelos treinados do zero e outros modelos pre-treinados disponiveis publicamente, em analise de sentimento, classificacao de textos e previsao de sentencas.",
     "Diversas tarefas de PLN em portugues brasileiro.",
     "ALTA",
     "E o PONTO DE PARTIDA do FinBERT-PT-BR e um dos encoders que ja testamos. Os autores indicam explicitamente a utilidade do BERTimbau para analise de sentimento no mercado financeiro - foi essa indicacao que motivou Santos. E a referencia para justificar por que partimos de modelo PT-BR e nao de traducao para o ingles."),
    (25,
     "SUN, C.; QIU, X.; XU, Y.; HUANG, X. How to fine-tune BERT for text classification? In: CCL, 2019. p. 194-206.",
     "2019", "A - Fundamentos / protocolo experimental",
     "Estrategias de fine-tuning; taxas de aprendizado; layer-wise decay; pre-treino de dominio",
     "Investigar sistematicamente como ajustar o BERT para classificacao de texto.",
     "Conjunto consolidado de recomendacoes, entre elas lr = 2e-5 para fine-tuning de modelo de linguagem.",
     "Protocolo experimental de ajuste fino.",
     "ALTA",
     "E a FONTE do lr = 2e-5 que Santos usa e que devemos usar no MLM de dominio. E tambem a referencia para justificar metodologicamente os hiperparametros do nosso experimento perante a banca, em vez de apresenta-los como escolha arbitraria."),
    (26,
     "TAN, K. L.; LEE, C. P.; LIM, K. M. A survey of sentiment analysis: approaches, datasets, and future research. Applied Sciences, v. 13, n. 7, 2023.",
     "2023", "B - Surveys",
     "Revisao de abordagens, datasets e direcoes de pesquisa",
     "Revisar de forma atualizada a area de analise de sentimento.",
     "Panorama atualizado de abordagens e conjuntos de dados; aponta direcoes futuras.",
     "Mapeamento de area.",
     "ALTA",
     "E a revisao MAIS RECENTE citada por Santos e esta publicada em periodico com fator de impacto, o que a torna citacao forte. Deve entrar na nossa RSL e serve ao argumento de atualidade do referencial."),
    (27,
     "VASWANI, A. et al. Attention is all you need. Advances in Neural Information Processing Systems, v. 30, 2017.",
     "2017", "A - Fundamentos / arquitetura",
     "Transformer; self-attention; multi-head attention",
     "Substituir recorrencia e convolucao por mecanismos de atencao puros.",
     "Estado da arte em traducao automatica com menor custo de treinamento.",
     "Arquitetura base de toda a familia BERT.",
     "MEDIA",
     "Citacao obrigatoria no capitulo teorico. A monografia de Santos (Figuras 4 e 5) traz um detalhamento didatico das camadas de self-attention e multi-head attention que pode ser adaptado a nossa fundamentacao."),
    (28,
     "XAVIER, F.; OLENSCKI, J. R. W.; ACOSTA, A. L.; SALLUM, M. A. M.; SARAIVA, A. M. Analise de redes sociais como estrategia de apoio a vigilancia em saude durante a COVID-19. Estudos Avancados, v. 34, n. 99, p. 261-282, 2020.",
     "2020", "D - Sentimento em portugues",
     "Analise de redes sociais; PLN aplicado a saude publica",
     "Demonstrar o uso de analise de dados de redes sociais no apoio a vigilancia em saude.",
     "Evidencia de aplicabilidade de analise de redes sociais em vigilancia epidemiologica.",
     "Saude publica.",
     "BAIXA",
     "Dominio de saude publica. Utilidade apenas ilustrativa, para demonstrar a amplitude de aplicacao de analise de sentimento em PT-BR."),
]

# Referencias presentes SOMENTE na monografia de 2022 (nao constam do artigo),
# incluidas por serem diretamente acionaveis no contexto atual da pesquisa.
REFS_MONOGRAFIA = [
    (29,
     "POURSABZI-SANGDEH, F.; BOYD-GRABER, J. Speeding document annotation with topic models. In: NAACL Student Research Workshop, 2015. p. 126-132. [SOMENTE NA MONOGRAFIA]",
     "2015", "F - Exclusiva da monografia",
     "Modelagem de topicos aplicada ao apoio a anotacao manual",
     "Acelerar a anotacao de documentos apresentando ao anotador informacao de modelos de topicos.",
     "Ganho de eficiencia quando anotadores recebem informacao de modelos de topicos.",
     "Construcao de corpora anotados com custo reduzido.",
     "MUITO ALTA (contexto atual)",
     "E a RESPOSTA TECNICA ao problema levantado pelo Prof. Emerson. Se a rotulagem for retomada, a modelagem de topicos permite (i) pre-selecionar textos representativos, reduzindo o volume a rotular, e (ii) apresentar sugestao de classe ao anotador, reduzindo a carga cognitiva e mitigando a falta de especializacao em financas."),
    (30,
     "ALCOFORADO, A. et al. ZeroBERTo: leveraging zero-shot text classification by topic modeling. arXiv:2201.01337, 2022. [SOMENTE NA MONOGRAFIA]",
     "2022", "F - Exclusiva da monografia",
     "Classificacao zero-shot; modelagem de topicos; linguas de poucos recursos",
     "Viabilizar classificacao zero-shot de texto em linguas com poucos recursos, via modelagem de topicos e clusterizacao.",
     "Alternativa ao XLM-R para zero-shot em portugues, com arquitetura adequada a linguas de poucos recursos.",
     "Classificacao de texto sem dados rotulados.",
     "ALTA",
     "Permite obter uma PRE-CLASSIFICACAO SEM ROTULO ALGUM - mais uma linha de trabalho compativel com a suspensao da rotulagem manual determinada pelo Prof. Emerson."),
    (31,
     "EFRON, B. Bootstrap methods: another look at the jackknife. In: Breakthroughs in statistics. Springer, 1992. p. 569-593. [SOMENTE NA MONOGRAFIA]",
     "1992", "F - Exclusiva da monografia",
     "Bootstrap; reamostragem com reposicao; intervalos de confianca empiricos",
     "Estimar a variabilidade de estatisticas por reamostragem com reposicao.",
     "Metodo geral para construcao de intervalos de confianca empiricos.",
     "Validacao estatistica de metricas de modelos.",
     "ALTA",
     "Fundamenta os intervalos de confianca que precisamos calcular sobre a nossa tabela de comparacao de encoders (resultado_encoders_petr4.csv), que hoje reporta diferencas de -1,67 pp a -16,00 pp SEM teste de significancia. Santos aplica bootstrap + teste Z e obtem p-valor ~0."),
]


def main() -> None:
    destino = Path(__file__).parent / "referencias_artigo_bwaif_24960.csv"
    linhas = REFS + REFS_MONOGRAFIA

    # utf-8-sig para que o Excel abra os acentos corretamente
    with destino.open("w", encoding="utf-8-sig", newline="") as fh:
        escritor = csv.writer(fh, delimiter=";", quoting=csv.QUOTE_ALL)
        escritor.writerow(COLUNAS)
        escritor.writerows(linhas)

    do_artigo = len(REFS)
    print(f"OK -> {destino.name}")
    print(f"  {do_artigo} referencias do artigo BWAIF n. 24960")
    print(f"  {len(REFS_MONOGRAFIA)} referencias adicionais exclusivas da monografia")
    print(f"  {len(linhas)} linhas no total")


if __name__ == "__main__":
    main()
